package ecologylab.translators.java.generics;

/**
 * Automatically generated by JavaTranslator on 11/07/11
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2011) Interface Ecology Lab.
 */

import ecologylab.serialization.annotations.Hint;
import ecologylab.serialization.annotations.simpl_hints;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import java.lang.Object;
import java.lang.String;

@simpl_inherit
public class SearchResult extends Object
{
	@simpl_scalar
	@simpl_hints({Hint.XML_ATTRIBUTE})
	private String title;

	public SearchResult()
	{ }

	public String getTitle()
	{
		return title;
	}

	public void setTitle(String title)
	{
		this.title = title;
	}
}
