package ecologylab.translators.java.generics;

/**
 * Automatically generated by JavaTranslator on 11/07/11
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2011) Interface Ecology Lab.
 */

import java.util.List;

import ecologylab.serialization.ElementState;
import ecologylab.serialization.annotations.Hint;
import ecologylab.serialization.annotations.simpl_collection;
import ecologylab.serialization.annotations.simpl_hints;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;

@simpl_inherit
public class Search<T extends SearchResult> extends ElementState
{
	@simpl_scalar
	@simpl_hints({Hint.XML_ATTRIBUTE})
	private String query;

	@simpl_collection("search_result")
	private List<T> searchResults;

	public Search()
	{ }

	public String getQuery()
	{
		return query;
	}

	public void setQuery(String query)
	{
		this.query = query;
	}

	public List<T> getSearchResults()
	{
		return searchResults;
	}

	public void setSearchResults(List<T> searchResults)
	{
		this.searchResults = searchResults;
	}
}
