package ecologylab.translators.java.generics;

/**
 * Automatically generated by JavaTranslator on 11/07/11
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2011) Interface Ecology Lab.
 */

import ecologylab.serialization.annotations.Hint;
import ecologylab.serialization.annotations.simpl_hints;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import ecologylab.translators.java.generics.SearchResult;
import java.lang.String;

@simpl_inherit
public class SocialSearchResult extends SearchResult
{
	@simpl_scalar
	@simpl_hints({Hint.XML_ATTRIBUTE})
	private String authorName;

	public SocialSearchResult()
	{ }

	public String getAuthorName()
	{
		return authorName;
	}

	public void setAuthorName(String authorName)
	{
		this.authorName = authorName;
	}
}
