package ecologylab.translators.java.generics;

/**
 * Automatically generated by JavaTranslator
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2012) Interface Ecology Lab.
 */

import ecologylab.serialization.annotations.Hint;
import ecologylab.serialization.annotations.simpl_hints;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import ecologylab.translators.java.generics.Search;
import ecologylab.translators.java.generics.SearchResult;
import ecologylab.translators.java.generics.SocialSearchResult;
import java.lang.String;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@simpl_inherit
public class SocialSearch extends Search<SocialSearchResult>
{
	@simpl_scalar
	@simpl_hints({Hint.XML_ATTRIBUTE})
	private long userId;

	public SocialSearch()
	{ super(); }

	public long getUserId()
	{
		return userId;
	}

	public void setUserId(long userId)
	{
		this.userId = userId;
	}
}
