package ecologylab.translators.java.generics;

/**
 * Automatically generated by JavaTranslator on 11/07/11
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2011) Interface Ecology Lab.
 */

import ecologylab.serialization.annotations.Hint;
import ecologylab.serialization.annotations.simpl_hints;
import ecologylab.serialization.annotations.simpl_inherit;
import ecologylab.serialization.annotations.simpl_scalar;
import ecologylab.translators.java.generics.Search;
import ecologylab.translators.java.generics.SearchResult;
import java.lang.String;
import java.util.ArrayList;

@simpl_inherit
public class SocialSearch extends Search
{
	@simpl_scalar
	@simpl_hints({Hint.XML_ATTRIBUTE})
	private long userId;

	public SocialSearch()
	{ }

	public long getUserId()
	{
		return userId;
	}

	public void setUserId(long userId)
	{
		this.userId = userId;
	}
}
