package library_tscope;

import ecologylab.semantics.metadata.builtins.MetadataBuiltinsTranslationScope;
import ecologylab.semantics.namesandnums.SemanticsNames;
import ecologylab.serialization.SimplTypesScope;

/**
 * Automatically generated by JavaTranslator on 11/07/11
 *
 * DO NOT modify this code manually: All your changes may get lost!
 *
 * Copyright (2011) Interface Ecology Lab.
 */


public class LibraryTranslationScope
{

	protected static final Class TRANSLATIONS[] =
	{
		ecologylab.translators.java.generics.Search.class,

		ecologylab.translators.java.generics.SearchResult.class,

		ecologylab.translators.java.generics.SocialSearch.class,

		ecologylab.translators.java.generics.SocialSearchResult.class,

	};

	public static SimplTypesScope get()
	{
		return SimplTypesScope.get(SemanticsNames.REPOSITORY_METADATA_TRANSLATIONS, MetadataBuiltinsTranslationScope.get(), TRANSLATIONS);
	}

}
